// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeManager.Data;

#nullable disable

namespace RecipeManager.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20251112150735_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeManager.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Breakfast",
                            RecipeId = 0
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Lunch",
                            RecipeId = 0
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Dinner",
                            RecipeId = 0
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Dessert",
                            RecipeId = 0
                        });
                });

            modelBuilder.Entity("RecipeManager.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrepTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.HasKey("RecipeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            CategoryId = 1,
                            Description = "Fluffy homemade pancakes.",
                            Ingredients = "Flour, Eggs, Milk, Sugar, Baking Powder",
                            Instructions = "Mix ingredients, cook on skillet.",
                            Name = "Pancakes",
                            PrepTime = "20 mins",
                            Servings = 4
                        },
                        new
                        {
                            RecipeId = 2,
                            CategoryId = 1,
                            Description = "Classic cheese omelette.",
                            Ingredients = "Eggs, Cheese, Salt, Pepper",
                            Instructions = "Beat eggs, cook with cheese.",
                            Name = "Omelette",
                            PrepTime = "10 mins",
                            Servings = 2
                        },
                        new
                        {
                            RecipeId = 3,
                            CategoryId = 2,
                            Description = "Golden grilled cheese sandwich.",
                            Ingredients = "Bread, Cheese, Butter",
                            Instructions = "Butter bread, grill with cheese.",
                            Name = "Grilled Cheese Sandwich",
                            PrepTime = "15 mins",
                            Servings = 1
                        },
                        new
                        {
                            RecipeId = 4,
                            CategoryId = 2,
                            Description = "Fresh Caesar salad with dressing.",
                            Ingredients = "Lettuce, Croutons, Caesar Dressing",
                            Instructions = "Mix lettuce, add dressing and croutons.",
                            Name = "Caesar Salad",
                            PrepTime = "15 mins",
                            Servings = 2
                        },
                        new
                        {
                            RecipeId = 5,
                            CategoryId = 3,
                            Description = "Classic Italian pasta dish.",
                            Ingredients = "Spaghetti, Ground Beef, Tomato Sauce",
                            Instructions = "Cook pasta, prepare sauce, mix together.",
                            Name = "Spaghetti Bolognese",
                            PrepTime = "45 mins",
                            Servings = 4
                        },
                        new
                        {
                            RecipeId = 6,
                            CategoryId = 3,
                            Description = "Spicy chicken curry.",
                            Ingredients = "Chicken, Curry Paste, Coconut Milk",
                            Instructions = "Cook chicken, add curry paste and coconut milk.",
                            Name = "Chicken Curry",
                            PrepTime = "60 mins",
                            Servings = 4
                        },
                        new
                        {
                            RecipeId = 7,
                            CategoryId = 4,
                            Description = "Rich chocolate cake.",
                            Ingredients = "Flour, Cocoa Powder, Sugar, Eggs",
                            Instructions = "Mix ingredients, bake in oven.",
                            Name = "Chocolate Cake",
                            PrepTime = "90 mins",
                            Servings = 8
                        },
                        new
                        {
                            RecipeId = 8,
                            CategoryId = 4,
                            Description = "Healthy fruit salad.",
                            Ingredients = "Apples, Bananas, Grapes, Oranges",
                            Instructions = "Chop fruits, mix together.",
                            Name = "Fruit Salad",
                            PrepTime = "10 mins",
                            Servings = 2
                        },
                        new
                        {
                            RecipeId = 9,
                            CategoryId = 3,
                            Description = "Mexican-style tacos.",
                            Ingredients = "Tortillas, Beef, Lettuce, Cheese",
                            Instructions = "Cook beef, assemble tacos.",
                            Name = "Tacos",
                            PrepTime = "30 mins",
                            Servings = 3
                        },
                        new
                        {
                            RecipeId = 10,
                            CategoryId = 1,
                            Description = "Sweet French toast.",
                            Ingredients = "Bread, Eggs, Milk, Cinnamon",
                            Instructions = "Dip bread in egg mixture, fry until golden.",
                            Name = "French Toast",
                            PrepTime = "20 mins",
                            Servings = 2
                        });
                });

            modelBuilder.Entity("RecipeManager.Models.Recipe", b =>
                {
                    b.HasOne("RecipeManager.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RecipeManager.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
